name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:                     
      REPOSITORY_OWNER: ${{ gitea.repository_owner }}
      REPOSITORY: ${{ gitea.repository }}
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }} 

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: gitea.mfec.co.th
        username: ${{ env.REPOSITORY_OWNER }}
        password: ${{ env.PERSONAL_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: gitea.mfec.co.th/${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY }}-tests:latest